### ISSUE TITLE
test/asm/null-in-macro.asm fails

### ISSUE THREAD

**Issue by bentley** [rednex/rgbds#50]
The newly added `test/asm/null-in-macro.asm` crashes.

The 0 byte embedded in the source code results in a zero‐length string buffer, which then gets assigned to.

```
Starting program: /home/anthony/bin/rgbasm null-in-macro.asm

Program received signal SIGSEGV, Segmentation fault.
0x00001112c5504427 in copymacro () at asmy.y:226
226     asmy.y: No such file or directory.
        in asmy.y
(gdb) bt
#0  0x00001112c5504427 in copymacro () at asmy.y:226
#1  0x00001112c5506e68 in yyparse () at asmy.y:643
#2  0x00001112c550aa84 in main (argc=Variable "argc" is not available.
) at src/asm/main.c:334
```

**Comment by AntonioND** [comment]
This doesn't crash to me, I suppose https://github.com/rednex/rgbds/issues/115 fixed it.

**Comment by Ben10do** [comment]
Yup, #115 fixed perhaps the most important reason for this crash.
